- name: Deploy Hotel Management System
  hosts: prod
  become: true
  vars_files:
    - ../group_vars/prod.yml
  vars:
    release_id: "{{ ansible_date_time.epoch }}"
  pre_tasks:
    - name: Ensure base dirs exist (server-side)
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: "0755"
      loop:
        - "{{ server_releases }}"
        - "{{ server_shared }}"
        - "{{ server_shared }}/uploads"
        - "{{ server_shared }}/uploads/avatars"
        - "{{ server_shared }}/migrations"
  tasks:
    - import_tasks: ../roles/app/tasks/main.yml
